// src/app/layout.tsx
import '@/lib/amplifyClient'; // ✅ must be before any Amplify usage
import type { Metadata } from 'next';
import { geistSans, geistMono } from '@/lib/fonts'; // ✅ moved here
import './globals.css';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}